### ISSUE TITLE
5268AC pfSense Services > Shellcmd scripts

### ISSUE THREAD

**Issue by ivanfarkas2** [MonkWho/pfatt#25]
I have **5268AC**.
If I understood it correctly in [Install](https://github.com/MonkWho/pfatt#install) step 3, I do have to setup all 3 scripts in pfSense Services > Shellcmd, right?

- pfatt.sh
- pfatt-5268AC.sh
- pfatt-5268AC-startup.sh

**Comment by ReignBock** [comment]
No, pfatt.sh is the only one that needs to be setup in shellcmd.

**pfatt.sh** is run via earlyshellcmd so it executes before pfsense loads its configuration. This is because pfatt.sh creates the ngeth0 interface and if that didn't exist before loading your configuration you'd need to choose a new WAN interface every reboot.

By placing **pfatt-5268AC-startup.sh** in /usr/local/etc/rc.d/ it is treated as a service and pfsense will execute the rc_start() function automatically. 

**pfatt-5268AC.sh** is then started by **pfatt-5268AC-startup.sh**

**Comment by ivanfarkas2** [comment]
So Sorry. It is very clear from the documentation. I have not paid attention to it. Thx, Ivan
