### ISSUE TITLE
Setting up static IPs on pfsense

### ISSUE THREAD

**Issue by MatthewGCampbell** [MonkWho/pfatt#28]
have a /29 block with AT&T and im trying to get it to pass the IPs through the NAT but im unsure if this needs a 1:1 nat, or just a basic nat rule to exclude the IPs from pfsenses NAT table, anyone have a setup like this? Trying to get the static ips to various physical interfaces and dont want to use vlans.

**Comment by MonkWho** [comment]
Yet again we haven't seen anyone mention configs like this. Better place to check would probably be netgate forums or reddit.

**Comment by owenthewizard** [comment]
I have a /29 block working - here's my setup, with OPNSense 20.1.7 and commit 90f5abb:

1. Setup OPNSense with pfatt as you usually would, including a DHCP public IP on the WAN interface. At this step you should have a "normal" setup, without your static IPs.
2. Navigate to Interfaces -> [WAN] (replace with your WAN interface name). Scroll down to **Alias IPv4 address**, and enter the **RG IP** AT&T provided you. For me, this was one past my last usable static IP.
3. Navigate to Firewall -> NAT -> One-to-One. Create a new One-to-One NAT rule, with the below values:
  Interface: **WAN**
  External Network: _**\<your desired useable static IP\>**_
  Source (Single Host or Network): _**\<IP of your LAN host or network that you want to use the static public IP\>**_ (Set the subnet mask accordingly - for a single device use /32)

**Comment by MonkWho** [comment]
Excellent write-up @owenthewizard. Thank you for contributing.

**Comment by MatthewGCampbell** [comment]
Very much appreciated for your help, owenthewizard

**Comment by owenthewizard** [comment]
I forgot to add my source, I struggled with this for a while before I found this: https://reddit.com/r/PFSENSE/comments/c08qyt/wan_static_ip_issues/er34dkb. Gracious hat tip to that lady/gentleman!

**Comment by owenthewizard** [comment]
I think adding this to the README could be useful - even though it's not directly related to the bypass. Thoughts?

**Comment by MonkWho** [comment]
This definitely looks like something that should be added to the readme. Unfortunately I don't have the time currently to write it up all nice and coherent. Could someone please write it up and create a pull request so I can just merge it?

**Comment by MatthewGCampbell** [comment]
I maybe could, I haven’t had time to play with it but this weekend I hope to get it working. 
Will ask for a pull request then.

**Comment by AndrewReaganM** [comment]
Here is at least a starting point. On my PFSense box I do not have a `Source` option on the new 1:1 rule page. Mine has `Internal IP` and `Destination`. I assume `Internal IP` is correct?


# Static IP Setup
If you have a static IPv4 block with AT&T, you can use it with your pfatt configuration. Note that in order to use your IPv4 block, you must set up your connection as stated above first. The normal installation, including setting up DHCP to get a public IP on the WAN interface, should be completed before the steps below.

1. Navigate to _Interfaces > WAN_ and scroll down to **Alias IPv4 address**.
1. Enter the RG IP address that AT&T provided to you. This is typically one past your last usable static IP.
1. Navigate to _Firewall > NAT > 1:1_.
1. Create a new 1:1 NAT rule with the following values.
   1. Interface: **WAN**
   1. External Network: **your desired usable static IP**
   1. Internal IP: (Single Host or Network) **IP of the LAN host or network that you want to have the static IP.**
   1. Set the submask accordingly (single devices use `/32`)

**Comment by MatthewGCampbell** [comment]
Thats not what i'm trying to do Andrew i'm trying to get my public IP to be my local IP for a router im trying to cascade basically behind my Pfsense box for my lab. Im not trying to set a 1:1 with a local address.

**Comment by MatthewGCampbell** [comment]
if this helps any one [this ](https://drive.google.com/file/d/1Luo9ae9EfGScGboFK7fGF_FX9GCXdpnd/view?usp=sharing)is what im trying to do.

**Comment by MatthewGCampbell** [comment]
I will try my best and add all of this to the read me, thats guys for your help.
