### ISSUE TITLE
2.5.0 Compatibility? 

### ISSUE THREAD

**Issue by MatthewGCampbell** [MonkWho/pfatt#37]
Doesn’t seem to work after upgrading to 2.5.5 is it just not compatible?

**Comment by MonkWho** [comment]
As far as compatibility with 2.5.0 goes. It was tested and reported in the issue #22 that a user had no issues upgrading 2.4.5-p1 to 2.5.0 and pfatt worked afterwards. I assume you mean pfSense 2.5.0 since there is no 2.5.5 as of yet?

Can you please provide more details about your upgrade? Also what bypass method are you using? Any errors when running paff script?

**Comment by A-vesalius** [comment]
Working fine for me on 2.5.0-DEVELOPMENT (amd64) built on Fri Oct 23. I've been updating 2.5 development every week or so and have had no issue with my bridged bypass.

**Comment by MatthewGCampbell** [comment]
Ok yeah I narrowed it down to a bridged interface I had setup on pfsense that was my issue.

**Comment by MonkWho** [comment]
@MatthewGCampbell and @A-vesalius if you still have your pFsense 2.5 set up and have some free time could you please test latest releases and see if you are experiencing same issue as being reported in #41?

**Comment by MatthewGCampbell** [comment]
Netgate won’t support a prod. 2.5.0 so I’m staying on 2.4.5, so I don’t think I’ll be able to test, as swapping out for my box running 2.5.0 would create a self inflicted internet outage, which while people are working from home isn’t the best idea, and I don’t have netgate support to back me up if any issues come up.

>

**Comment by A-vesalius** [comment]
> @MatthewGCampbell and @A-vesalius if you still have your pFsense 2.5 set up and have some free time could you please test latest releases and see if you are experiencing same issue as being reported in #41?

Wish I could help, but I was using the bypass method previously and not supplicant.  Beyond that since I was running on proxmox, just this weekend I switched to utilizing group_fwd_mask to bridge 802.1X traffic from RG and to ONT. I was way overthinking the complexity and it is really easy to setup on proxmox in the end. Can now test out whatever virtual router I want to get out through the ONT over vlan0.
